services:
#  search_service:
#    build: .
#    container_name: search_service
#    depends_on:
#      - elastic_search
#      - kibana
#    networks:
#      - project_box_net
#    ports:
#      - "8081:8081"
#    restart: unless-stopped

  elastic_search:
    image: elasticsearch:8.16.0
    container_name: ${ELASTIC_CONTAINER_NAME}
    ports:
      - "${ELASTIC_HTTP_PORT}:9200"
      - "${ELASTIC_TCP_PORT}:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
      - xpack.security.enabled=${XPACK_SECURITY_ENABLED}
    networks:
      - project_box_net
    restart: unless-stopped
    tty: true

  kibana:
    image: kibana:8.16.0
    container_name: ${KIBANA_CONTAINER_NAME}
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic_search:9200
    ports:
      - "${KIBANA_PORT}:5601"
    volumes:
      - kibana_data:/usr/share/kibana/data
    restart: unless-stopped
    depends_on:
      - elastic_search
    networks:
      - project_box_net


networks:
  project_box_net:
    external: true
volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
