services:
  search_service:
    build: .
    container_name: search_service
    restart: unless-stopped
    ports:
      - "8081:8081"
    working_dir: /app
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    networks:
      - project_box_net

  elasticsearch:
    image: elasticsearch:8.16.0
    container_name: ${ELASTIC_CONTAINER_NAME}
    ports:
      - "${ELASTIC_HTTP_PORT}:9200"
      - "${ELASTIC_TCP_PORT}:9300"
    volumes:
      - ./src/main/java/com/example/search/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
      - xpack.security.enabled=${XPACK_SECURITY_ENABLED}
    networks:
      - project_box_net
    restart: unless-stopped
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 3

  kibana:
    image: kibana:8.16.0
    container_name: ${KIBANA_CONTAINER_NAME}
    environment:
      - ELASTICSEARCH_HOSTS=${KIBANA_ELASTICSEARCH_HOSTS}
    ports:
      - "${KIBANA_PORT}:5601"
    volumes:
      - kibana_data:/usr/share/kibana/data
    restart: unless-stopped
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - project_box_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  project_box_net:
    external: true

volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
