services:
  elasticsearch:
    image: elasticsearch:8.16.0
    container_name: elasticsearch
    ports:
      - "${ELASTIC_HTTP_PORT}:9200"
      - "${ELASTIC_TCP_PORT}:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    networks:
      - project_box_net
    restart: unless-stopped
    tty: true

  kibana:
    image: kibana:8.16.0
    container_name: ${KIBANA_CONTAINER_NAME}
    environment:
      - ELASTICSEARCH_HOSTS=${KIBANA_ELASTICSEARCH_HOSTS}
      - xpack.security.http.ssl.enabled=false
    ports:  
      - "${KIBANA_PORT}:5601"
    volumes:
     - kibana_data:/usr/share/kibana/data
    restart: unless-stopped
    depends_on:
      - elasticsearch
    networks:
      - project_box_net

networks:
   project_box_net:
     external: true

volumes:
  elasticsearch_data:
  kibana_data:
