services:
  elastic_search:
    image: elasticsearch:8.16.0
    container_name: elastic_search
    ports:
      - "9200:9200"  # HTTP port for accessing the REST API
      - "9300:9300"  # TCP transport port for inter-node communication (if using clusters)
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data  # Use a named volume for data persistence
    environment:
      - discovery.type=single-node  # Required for single-node Elasticsearch
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Optional: Set memory options (adjust as necessary)
      - xpack.security.enabled=false
    networks:
      - elk_network
    restart: unless-stopped
    tty: true

  kibana:
    image: kibana:8.16.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic_search:9200
    ports:
      - "5601:5601"
    volumes:
      - kibana_data:/usr/share/kibana/data  # Use a named volume for Kibana data persistence
    restart: unless-stopped
    depends_on:
      - elastic_search
    networks:
      - elk_network

networks:
  elk_network:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local  # Added named volume for Kibana
