services:
  search_service:
    image: kunmhing/searchservice:latest
    container_name: search_service
    restart: unless-stopped
    ports:
      - "8081:8081"
    working_dir: /app
    depends_on:
      - kibana
      - elasticsearch
    networks:
      - project-service_project_box_net

  elasticsearch:
    image: elasticsearch:8.16.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m 
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    networks:
      - project-service_project_box_net
    restart: unless-stopped
    tty: true

  kibana:
    image: kibana:8.16.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.http.ssl.enabled=false
    ports:  
      - "${KIBANA_PORT}:5601"
    volumes:
      - kibana_data:/usr/share/kibana/data
    restart: unless-stopped
    # depends_on:
    #   - kibana_data:/usr/share/kibana/data
    networks:
      - project-service_project_box_net

networks:
  project-service_project_box_net:
    external: true

volumes:
  elasticsearch_data:
  kibana_data:
